#pragma once
#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_RESET   "\x1b[0m"

#define PLAYER_ANSI_COLOR_RED     "\x1b[31m-\x1b[0m"
#define PLAYER_ANSI_COLOR_GREEN   "\x1b[32m-\x1b[0m"
#define PLAYER_ANSI_COLOR_YELLOW  "\x1b[33m-\x1b[0m"
#define PLAYER_ANSI_COLOR_BLUE    "\x1b[34m-\x1b[0m"
#define PLAYER_ANSI_COLOR_MAGENTA "\x1b[35m-\x1b[0m"
#define PLAYER_ANSI_COLOR_CYAN    "\x1b[36m-\x1b[0m"

#define WALL_ANSI_COLOR_RED     "\x1b[31m¡á\x1b[0m"
#define WALL_ANSI_COLOR_GREEN   "\x1b[32m¡á\x1b[0m"
#define WALL_ANSI_COLOR_YELLOW  "\x1b[33m¡á\x1b[0m"
#define WALL_ANSI_COLOR_BLUE    "\x1b[34m¡á\x1b[0m"
#define WALL_ANSI_COLOR_MAGENTA "\x1b[35m¡á\x1b[0m"
#define WALL_ANSI_COLOR_CYAN    "\x1b[36m¡á\x1b[0m"

#define DESTROYABLE_WALL_ANSI_COLOR_RED     "\x1b[31m#\x1b[0m"
#define DESTROYABLE_WALL_ANSI_COLOR_GREEN   "\x1b[32m#\x1b[0m"
#define DESTROYABLE_WALL_ANSI_COLOR_YELLOW  "\x1b[33m#\x1b[0m"
#define DESTROYABLE_WALL_ANSI_COLOR_BLUE    "\x1b[34m#\x1b[0m"
#define DESTROYABLE_WALL_ANSI_COLOR_MAGENTA "\x1b[35m#\x1b[0m"
#define DESTROYABLE_WALL_ANSI_COLOR_CYAN    "\x1b[36m#\x1b[0m"